remote_theme: pmarsceill/just-the-docs
title: "Handbook for HC MID projects"

aux_links:
  "source on github":
    - "https://github.com/HCMID/tutorial2021"


footer_content: "Citable, verified, collaborative editing, backed by visual evidence."
