theme: "just-the-docs"
title: "HC MID tutorial materials"

aux_links:
  "source on github":
    - "https://github.com/HCMID/tutorial2021"


footer_content: "Citable, verified, collaborative editing, backed by visual evidence."
